apiVersion: v1
kind: Service
metadata:
  name: k8s-jenkins-app-service
  labels:
    app: k8s-jenkins-app
spec:
  type: NodePort
  selector:
    app: k8s-jenkins-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
